platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Add your dependencies here
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure 'flutter pub get' is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    if match = line.match(/FLUTTER_ROOT\=(.*)/)
      return match[1].strip
    end
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

# Specify your dependencies here
target 'Runner' do
  # Uncomment this line if you're using Firebase
  # use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # Add other pods as needed for your project

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
